django/MyBlog/MyBlog/urls.py
from django.contrib import admin
from django.urls import path,include
import app_01.urls
from MyBlog.views import *


app_name='MyBlog'
urlpatterns = [
    path('blog/',include(app_01.urls,)),
    path('login/user/',login_view),
    path('register/user/',register_view),
    path('login/',login_page,name='login_page'),
    path('register/',register_page,name='register_page'),
    path('about/',get_about,name='about'),
    path('contact/',get_contact,name='contact'),
    path('admin/', admin.site.urls),
]

django/MyBlog/app_01/urls.py
from django.urls.conf import path,re_path,include
from app_01.views import *
from haystack import urls

app_name='app_01'
urlpatterns=[
    re_path(r'^index/(\d?/?)$',get_page,name='blog_page'),
    path(r'posts/',blogs,name='blogs_page'),
    path(r'cgy/<str:category_name>',cgy_view,name='cgy_page'),
    path(r'tag/<str:tag_name>',tag_view,name='tag_page'),
    path(r'post/<str:blog_title>',blog_view,name='blog_content'),
    path(r'search/',SearchHandler(),name='haystack_search'),
]

django/MyBlog/templates/base/about.html
<!DOCTYPE html>
<html>
	<head>
		<title>Black &amp; White</title>

		<!-- meta -->
		<meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">

	    <!-- css -->
		<link rel="stylesheet" href="css/bootstrap.min.css">
		<link rel="stylesheet" href="css/ionicons.min.css">
		<link rel="stylesheet" href="css/pace.css">
	    <link rel="stylesheet" href="css/custom.css">

	    <!-- js -->
	    <script src="js/jquery-2.1.3.min.js"></script>
	    <script src="js/bootstrap.min.js"></script>
	    <script src="js/pace.min.js"></script>
	    <script src="js/modernizr.custom.js"></script>
	</head>

	<body id="page">
		<div class="container">	
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							<h1><a href="index.html"><b>Black</b> &amp; White</a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="index.html" data-hover="Home">Home</a></li>
    								<li class="cl-effect-11"><a href="full-width.html" data-hover="Blog">Blog</a></li>
    								<li class="cl-effect-11"><a href="about.html" data-hover="About">About</a></li>
    								<li class="cl-effect-11"><a href="contact.html" data-hover="Contact">Contact</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="Search" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>				
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">About Me</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<figure class="img-responsive-center">
									<img class="img-responsive" src="img/me.jpg" alt="Developer Image">
								</figure>
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<p>Responsive web design offers us a way forward, finally allowing us to design for the ebb and flow of things. There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don’t look even slightly.</p>
								<div class="height-40px"></div>
								<h2 class="title text-center">Social</h2>
								<ul class="social">
									<li class="facebook"><a href="#"><span class="ion-social-facebook"></span></a></li>
									<li class="twitter"><a href="#"><span class="ion-social-twitter"></span></a></li>
									<li class="google-plus"><a href="#"><span class="ion-social-googleplus"></span></a></li>
									<li class="tumblr"><a href="#"><span class="ion-social-tumblr"></span></a></li>
								</ul>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2014 ThemeWagon.com</p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a href="full-width.html">Blog</a></li>
					<li><a href="about.html">About</a></li>
					<li><a href="contact.html">Contact</a></li>
				</ul>
			</nav>
		</div>

		<script src="js/script.js"></script>
		
	</body>
</html>

django/MyBlog/templates/base/contact.html
<!DOCTYPE html>
<html>
	<head>
		<title>Black &amp; White</title>

		<!-- meta -->
		<meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1">

	    <!-- css -->
		<link rel="stylesheet" href="css/bootstrap.min.css">
		<link rel="stylesheet" href="css/ionicons.min.css">
		<link rel="stylesheet" href="css/pace.css">
	    <link rel="stylesheet" href="css/custom.css">

	    <!-- js -->
	    <script src="js/jquery-2.1.3.min.js"></script>
	    <script src="js/bootstrap.min.js"></script>
	    <script src="js/pace.min.js"></script>
	    <script src="js/modernizr.custom.js"></script>
	</head>

	<body id="page">
		<div class="container">	
			<header id="site-header">
				<div class="row">
					<div class="col-md-4 col-sm-5 col-xs-8">
						<div class="logo">
							<h1><a href="index.html"><b>Black</b> &amp; White</a></h1>
						</div>
					</div><!-- col-md-4 -->
					<div class="col-md-8 col-sm-7 col-xs-4">
						<nav class="main-nav" role="navigation">
							<div class="navbar-header">
  								<button type="button" id="trigger-overlay" class="navbar-toggle">
    								<span class="ion-navicon"></span>
  								</button>
							</div>

							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  								<ul class="nav navbar-nav navbar-right">
    								<li class="cl-effect-11"><a href="index.html" data-hover="Home">Home</a></li>
    								<li class="cl-effect-11"><a href="full-width.html" data-hover="Blog">Blog</a></li>
    								<li class="cl-effect-11"><a href="about.html" data-hover="About">About</a></li>
    								<li class="cl-effect-11"><a href="contact.html" data-hover="Contact">Contact</a></li>
  								</ul>
							</div><!-- /.navbar-collapse -->
						</nav>
						<div id="header-search-box">
							<a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
							<div id="search-form" class="search-form">
								<form role="search" method="get" id="searchform" action="#">
									<input type="search" placeholder="Search" required>
									<button type="submit"><span class="ion-ios-search-strong"></span></button>
								</form>				
							</div>
						</div>
					</div><!-- col-md-8 -->
				</div>
			</header>
		</div>

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">Contact</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<form action="#" method="post" class="contact-form">
									<div class="row">
										<div class="col-md-6 col-md-offset-3">
											<input type="text" name="name" placeholder="Name" required>
											<input type="email" name="email" placeholder="Email" required>
											<input type="text" name="subject" placeholder="Subject" required>
											<textarea name="message" rows="7" placeholder="Your Message" required></textarea>
											<button class="btn-send btn-5 btn-5b ion-ios-paperplane"><span>Drop Me a Line</span></button>
										</div>
									</div>	<!-- row -->
								</form>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2014 ThemeWagon.com</p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a href="full-width.html">Blog</a></li>
					<li><a href="about.html">About</a></li>
					<li><a href="contact.html">Contact</a></li>
				</ul>
			</nav>
		</div>

		<script src="js/script.js"></script>
		
	</body>
</html>

django/MyBlog/templates/base/error.html
<!DOCTYPE HTML>
<html>

</html>

django/MyBlog/templates/base/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!--meta-->
    <meta charset="utf-8">
    <meta name="author" content="Jack,jule,12,2017">
    <meta name="Keywords" content="html,blog,python,django">
</head>
<title >博客网</title>
<style type="text/css">
    body{
    font-size: 62.5%;
}
    body a:link{
    color:#000000;
    text-decoration: none;
}
    body a:visited,a:active{
    color:#0000CD;
    text-decoration: none;
}
    body a:hover{
    color: #003366;
    text-decoration: none;
}

.blog_title{
        font-size:300%;
        color:#003366;
        font-style: italic;
    }
.Navbar{
    width: 100%;
    overflow: hidden;
}
.Navbar_list{
    padding:0.5em 1em 1px 0.001em;
    width:100%;
    font-size:200%;
    list-style-type: None;

}
.Navbar li{
    display: inline;
    padding:0;
    margin:0;
}
.Navbar li a {
    color: #000;
}
.blog_upload{
    float:left;
    width: 70%;
    padding-bottom: 800px;
    margin-bottom: -800px;
}
.blog{
    font-size: 200%;
    font-weight:bold;
    color:#A52A2A;
}
.blog-title-01{
    font-size:150%;
    padding:0.5em;
    text-align: left;

}
.blog-content-01{
    font-size:180%;
    padding:0.1em 0.5em ;
}
.page_list{
    text-align: center;
}
.pagination_list{
    display: inline-block;
    padding: 2em;
    margin: 0;
    font-size: 200%;
}
.pagination_list li{
    display: inline;
}
.pagination_list li a{
    border:0.5px solid #8925ff ;
    padding:0.5em;

}
.pagination_list li a.active{
    background-color: #518900;
}
.pagination_list li a:hover :not(.active){
    background-color: #454545;
}
.container-02-right{
    float:right;
    width:30%;
    font-size: 100%;
    font-weight:bold;
    padding-bottom: 800px;
    margin-bottom: -800px;
}
.search{
    text-align: right;
    padding:2em;
}
.search-form{
    list-style-type: None;
    font-size: 150%;
}
.random-blog{
    text-align: left;
    font-size: 200%;
    padding: 0.5em;
    color:#A52A2A;
}
.blog-list{
    list-style-type: None;
}
.blog-list li{
    display: inline;
}
.blog-list.blog-author{
    float:left;
    color: #8925ff;
}
.blog-list.content-split{
    color:#000000;
}
.blog-list.blog-create{

}
.blog-content{

}
.blog-category{
    font-size: 200%;
    color: #A52A2A;
}
.blog-category ul{
    list-style-type: None ;
}

.blog-tag-title{
    font-size: 200%;
    color:#A52A2A;
}
.blog-tag-content{
    float:left;
    width:30%;
    padding:0.5em;
    font-size:170%;
}
.page-border{
    border-style:solid;
    border-radius:40px;
    border-color:#000000;
    border-width:1px;
    margin: 2em ;
}
.page-pagination{
    text-align: center;
    font-size: 200%;
}
.page-pagination ul{
    display: inline-block;
    padding: 0;
    margin: 0;
    list-style-type: none;
}
.page-pagination ul li{
    display: inline;
}
.page-pagination ul li a{
    color:black;
    float:left;
    padding:0.8em 1.6em;
}
.page-pagination ul li a.active{
    background: #003366;
    color:white;
}

</style>
<body>
<div class="blog_title" >欢迎来到,水溶C100</div>
<div class="Navbar">
    <ul class="Navbar_list" >
        <li><a href="{% url 'app_01:blog_page' 1 %}" data-hover="首页">首页</a></li>
        <li><a href="{% url 'app_01:blogs_page' %}" data-hover="博客">博客</a> </li>
        <li><a href="{% url 'about' %}" data-hover="关于">关于</a></li>
        <li><a href="{% url 'contact' %}" data-hover="联系">联系</a></li>
        <li><a href="{% url 'register_page'%}" data-hover="注册">注册</a></li>
        <li><a href="{% url 'login_page'%}" data-hover="登录">登录</a></li></ul></div><hr/>
<div class="blog_upload">
    <div class="blog" align="left">最近更新</div>
    {% for contact in contacts %}
    <div class="blog-title-01">
        <h2><a href="{% url 'app_01:blog_content' blog_title=contact.title %}">{{contact.title}}</a></h2>
    </div>
    <div class="blog-content-01" align="left">
        &nbsp&nbsp&nbsp&nbsp<a href="{% url 'app_01:blog_content' blog_title=contact.title %}">{{ contact.content | truncatewords_html:20 }}</a>
    </div>
    {% endfor %}
     <div class="page_list">
        <ul class="pagination_list">
            <!--  如果当前页有前一页，则上一页链接有效  -->
            {% if contacts.has_previous %}
                <li class="page" ><a href="{% url 'app_01:blog_page' contacts.previous_page_number %}"><</a></li>
            {% endif %}
            <!-- 取出页码数（页码数不一定就是总页数，有省略显示部分，具体在settings.py配置） -->
            {% load pagetag %}
            {% for pg in contacts.paginator.page_range %}
                {% circle_tag contacts.number pg  %}
            {% endfor %}
            <!-- 如果当前页有下一页，则下一页链接有效-->
            {% if contacts.has_next %}
                <li class="page" ><a href="{% url 'app_01:blog_page' contacts.next_page_number %}">></a></li>
            {% endif %}
        </ul></div>
        </div>
<div class="container-02-right">
    <div class="search">
        <form class="search-form" action="{% url 'app_01:haystack_search' %}" method="get">
            <input type="text"  placeholder="请输入要查询的文章标题" name="q">
            <input type="submit" value="搜索">
        </form>
    </div>
    <div class="random-blog" align="left">随机博客</div><hr/>
        {% for random_blog in random_blogs %}
            <div class="blog-cre">
            <ul class="blog-list">
                <li class="blog-title"><a href="{% url 'app_01:blog_content' blog_title=random_blog.title %}" >{{random_blog.title}}</a></li>
                <li class="content-split">&nbsp·&nbsp</li>
                <li class="blog-create">{{random_blog.create_time|date:"Y m d"}}</li>
            </ul>
            </div>
            <div class="blog-content">&nbsp&nbsp&nbsp&nbsp<a href="{% url 'app_01:blog_content' blog_title=random_blog.title %}">
                {{random_blog.content|truncatewords_html:10}}</a>
        {% endfor %}</div><br>
    <div class="blog-category">博客分类<hr/>
        {% for category,count in categorys_counts.items %}
    <ul class="categroy-list">
        <li class="blog-category-con"><a href="{% url 'app_01:cgy_page' category_name=category %}">{{ category}}</a>({{count}})</li>

    </ul>
        {% endfor %}
    </div>
<div class="blog-tag">
    <div class="blog-tag-title">标签</div><hr/>
        <div class="blog-tag-detail">
            {% for tag in tags  %}
                <div class="blog-tag-content"><a href="{% url 'app_01:tag_page' tag_name=tag %}">{{tag}}</a></div>
            {% endfor %}
        </div>
</div>
</div>
</body>
</html>

django/MyBlog/templates/base/login.html
<!DOCTYPE HTML>
<html>
<head>
    <title>用户登录</title>
    <meta charset="UTF-8">
    <meta name="author" content="Jack,jule,12,2017">
    <meta name="Keywords" content="Html,blog,python,django">
</head>
<body>
    <div class="form-control">
        <H1>登录</H1>
        <form action="/login/user/" method="post" id="login">
            {% csrf_token %}
            <ul>
                <li>
                    <input type="text" id="name" name="user_name" placeholder="Username" title="Name" required/>
                </li>
                <li>
                    <input type="password" class="lock" name="password" title="Minimum 8 characters, one number, one uppercase and one lowercase letter"
                            placeholder="Password" id="password1" required/>
                </li>
                <li>
                    <input type="submit" value="登录"/>
                </li>

            </ul>
        </form>
    </div>


</body>
</html>

django/MyBlog/templates/base/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{% if errors %}
    <ul>
        <li>
            {% for error in errors %}
             <p style="color: red;">
                {{error}}
             </p>
              {% endfor %}
        </li></ul>
    {% endif %}
<div>
    <form action="/register/user/" method="post">
        {% csrf_token %}
        <ul>
            <li>
                <label >用户名:</label>
            </li>
            <li>
                <input type = 'text' placeholder="输入用户名" name = 'account'>
            </li>
        </ul>
        <ul>
            <li>
                <label >密码:</label>
            </li>
            <li>
              <input type = 'password' placeholder="输入密码" name = 'password'>
            </li>
        </ul>
         <ul>
             <li>
                <label >确认密码:</label>
             </li>
             <li>
                 <input type = 'password' placeholder="再次输入密码" name ='password2'>
             </li>

         </ul>
         <ul>
             <li>
                 <label>邮箱:</label>
             </li>
             <li>
                 <input type="email" placeholder="输入邮箱" name = 'email'>
             </li>
         </ul>
          <ul>

              <li>
                   <input type = 'submit' placeholder="Login" value="登录">
              </li>
          </ul>
    </form>
</div>
</body>
</html>

django/MyBlog/templates/base/update.html
{% extends "base.html" %}
{% block blog-upload %}
<div class="blog" align="left">最近更新</div>
    {% for contact in contacts %}
    <div class="blog-title-01" align="left">
        <h2><a href="blog_content.html">{{contact.title}}</a></h2>
    </div>
    <div class="blog-content-01" align="left">
        &nbsp&nbsp&nbsp&nbsp{{ contact.content | truncatewords_html:20 }}
    </div>
    {% endfor %}
<div class="page-border" >
<nav class="page-pagination">
<ul class="pagination">
        {% if contacts.has_previous %}
            <li>
            <a href="?page={{ contacts.previous_page_number }}" aria-label="previous">
            <span aria-hidden="true">&laquo;</span>
            </a></li>
        {% endif %}
        {% for pg in contacts.paginator.page_range %}
            {% circle_page contacts.number pg %}
        {% endfor %}
        {% if contacts.has_next %}
            <li>
            <a href="?page={{ contacts.next_page_number }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span></a></li>
        {% endif %}

</ul>
</nav></div>
{% endblock %}